[package]
name = "cdf"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
paste = "1.0.15"
serde_json = "1.0.148"

[dependencies]
serde = { version = "1.0.228", features = ["derive"], optional = true }
